name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}
      run:
        docker login -u  ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hello-world-test:$(date +%s)

    - name: Docker Push
      run: docker push ${{secrets.DOCKERUSERNAME}}/hello-world-test
